// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xquarhirsodrwzbglxjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxdWFyaGlyc29kcnd6YmdseGp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwOTQ3NDMsImV4cCI6MjA4NjY3MDc0M30.kSWtRzctzgrlDEb_UCVCVVhkXrF2aGDb2f00RT8lJ2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});